name: Unit Tests

on: [push]

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:master

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dev-tools
        run: |
          install-dev-tools

      - name: Install dependencies
        run: |
          apt install python3-pytest-mock -y
          pip install --break-system-packages --ignore-installed .

      - name: Run Tests
        run: |
          pytest apps_validation/pytest/unit/
          pytest catalog_reader/pytest/unit/
          pytest apps_schema/pytest/unit/
          pytest apps_ci/pytest/unit/
